[package]
name = "fact-apis"
version = "0.1.0"
edition = "2021"
include = ["/static"]

[dependencies]
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]
